mouse:
  gestures:
    # down right: close window
    - type: stroke
      strokes: ['AAcALQUrFDIFXC/9ZFJkAA==']
      mouse_buttons: [right]
      keyboard_modifiers: none
      actions:
        - on: end
          input:
            - keyboard: [leftctrl+w]
    # up: home
    - type: stroke
      strokes: ['MmQA0TU6KcsuAGQA']
      mouse_buttons: [right]
      actions:
        - on: end
          input:
            - keyboard: [home]
      keyboard_modifiers: none
    # down: end
    - type: stroke
      strokes: ['LwAAMDRkZAA=']
      mouse_buttons: [right]
      actions:
        - on: end
          input:
            - keyboard: [end]
      keyboard_modifiers: none
    # up left: previous tab
    - type: stroke
      strokes: ['ZFoAzWELLJ4RCVpdAAxkAA==']
      mouse_buttons: [right]
      actions:
        - on: end
          input:
            - keyboard: [leftctrl+pageup]
      keyboard_modifiers: none
    # up right: next tab
    - type: stroke
      strokes: ['AFUAzwAPKABBDk8FZBVkAA==']
      mouse_buttons: [right]
      actions:
        - on: end
          input:
            - keyboard: [leftctrl+pagedown]
      keyboard_modifiers: none
